version: 0.0
os: linux
permissions:
   - object: /home/ubuntu
     pattern: "**"
     owner: ubuntu
     group: ubuntu
     mode: 777
hooks:
   ApplicationStart:
   - location: java -jar ./target/kinneret-server-1.0-SNAPSHOT.jar server kinneret-server-ubuntu.yml
     runas: ubuntu

