version: 0.0
os: linux
  - source: kinneret-server-ubuntu.yml
    destination: /home/ubuntu
  - source: target/kinneret-server-1.0-SNAPSHOT.jar
    destination: /home/ubuntu
permissions:
   - object: /home/ubuntu
     pattern: "**"
     owner: ubuntu
     group: ubuntu
     mode: 777
hooks:
   ApplicationStart:
   - location: $(which java) -jar /home/ubuntu/target/kinneret-server-1.0-SNAPSHOT.jar server /home/ubuntu/kinneret-server-ubuntu.yml
     runas: ubuntu

